name: agrictools
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.18.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  clipboard: ^0.1.3
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  flutter_dropzone: ^3.0.7
  flutter_typeahead: ^5.2.0
  connectivity_plus: ^5.0.1
  multi_select_flutter: ^4.1.3
  cached_network_image: ^3.3.0
  flutter_native_splash: ^2.3.5
  smooth_page_indicator: ^1.1.0
  pin_code_fields: 8.0.1
  

  # Web Specific
  web: ^0.5.1
  http: ^1.1.2
  html: ^0.15.4
  fl_chart: ^0.66.2
  data_table_2: ^2.5.9
  url_strategy: ^0.2.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
 